version: '3.8'

services:
  front:
    build: ./front
    ports:
      - "5000:5000"
    depends_on:
      - core

  core:
    build: ./core
    ports:
      - "5001:5001"

  load_tester:
    build: ./load_tester
    depends_on:
      - front
